### PR TITLE
fixed processing of whitespaces - missing CR character

### PR DESCRIPTION
**Pull request by janproch**

### CODE REVIEW

**Comment by MasterOdin** [comment]
Could you update the "scans white space" test in the tokenizer spec too include `\r`?

**Comment by maxcnunes** [comment]
@janproch thanks for the contribution. Just a FYI, in case you don't provide the test changes for this PR in the next week, I might take it over to finish it.

**Comment by janproch** [comment]
@maxcnunes Test updated. Sorry for unnecessary delay, it was deadly simple

**Comment by MasterOdin** [comment]
Thanks for the PR!

**Pull request merged**
